version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:13.13.0
    steps:
      - checkout
      - run: npm i
      - run: npm run lint
  test:
    docker:
      - image: circleci/node:13.13.0
    steps:
      - checkout
      - run: npm i
      - run: npm run test
  analyze:
    docker:
      - image: cimg/node:18.4.0
    steps:
      - checkout
      - run: npm audit
      # - run: npm audit fix --force
      # - run: npm audit fix --package-lock-only


workflows:
  my_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test